In [1]:
from numpy import random
x=random.randint(100,size=(2,3, 5))
print(x)
               

[[[88  6 30 93  4]
  [18 47 62 99 36]
  [75 76 24 35 31]]

 [[34 76 58 12 65]
  [50 55 88 37 80]
  [92 73  2 17 75]]]
